import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import react,{useState} from 'react'
import Link from 'next/link'
import { useRouter } from 'next/router'



export default function Home() {

  const [id,setId] = useState('')
  const router = useRouter()

const logar = () =>{
  axios.post('',{
    email:email,
    password:password
  }).then((response) =>{
    setId(response),
    router.push('/Home')
  }).catch((err) => alert('Erro na hora de acessar'))

 
}



  return (




    <div className={styles.Container} >
      <Head>
        <title>Controle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
    <div className={styles.inputContainer}>
     <input className={styles.inputStyle} type='email' placeholder='email'/>
     <input className={styles.inputStyle} type='password' placeholder='password'/>
     <button className={styles.btnStyle} onClick={ () => logar()}>ENTRAR</button>
    </div>
  
  
  </div>
)
  }